# ai_helper.py
# This file handles all AI functions using OpenRouter

import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# Connect to OpenRouter AI
client = OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1"
)

FREE_MODEL = "nvidia/nemotron-3-super-120b-a12b:free"


def extract_promotions(raw_text: str, bank_name: str) -> str:
    """
    Send scraped bank text to AI and get back organized promotions
    """
    print(f"    🤖 AI analyzing {bank_name} promotions...")
    
    try:
        response = client.chat.completions.create(
            model=FREE_MODEL,
            messages=[
                {
                    "role": "user",
                    "content": f"""You are a Hong Kong bank promotions analyst.
                    
Analyze this content from {bank_name} Hong Kong website and extract ALL promotions.

For each promotion, list:
- 📌 Promotion Name
- 💰 Offer (e.g. 5% cashback, 3x points, HK$100 discount)
- 💳 Eligible Cards/Accounts  
- 📅 Valid Period (dates if available)
- 💵 Minimum Spend (if any)
- 📝 Key Conditions

If no clear promotions found, write: "No active promotions found on this page."

Bank content to analyze:
---
{raw_text[:3000]}
---"""
                }
            ],
            max_tokens=1500,
            temperature=0.3
        )
        
        result = response.choices[0].message.content
        print(f"    ✅ AI extraction complete for {bank_name}")
        return result
        
    except Exception as e:
        error_msg = f"AI extraction failed for {bank_name}: {str(e)}"
        print(f"    ❌ {error_msg}")
        return error_msg


def create_email_digest(promotions_data: list) -> str:
    """
    Take all bank promotions and create a nice email summary
    """
    print("\n🤖 AI creating email digest...")
    
    # Combine all bank promotions into one text
    all_promotions = ""
    for item in promotions_data:
        all_promotions += f"\n\n{'='*40}\n"
        all_promotions += f"BANK: {item['bank']}\n"
        all_promotions += f"{'='*40}\n"
        all_promotions += item['promotions']
    
    try:
        response = client.chat.completions.create(
            model=FREE_MODEL,
            messages=[
                {
                    "role": "user",
                    "content": f"""Create a weekly Hong Kong Bank Promotions Digest email in plain text.

FORMAT:
1. Start with title: "🏦 HK Bank Promotions Weekly Digest"
2. Add today's date
3. Section: "⭐ TOP 3 BEST DEALS THIS WEEK" (pick the best 3 overall)
4. Then section for each bank with their promotions
5. Use these category emojis: 🍽️ Dining | ✈️ Travel | 🛍️ Shopping | 💰 Cashback | 🏠 Home | 🎉 Entertainment
6. End with: "📧 This digest was auto-generated by HK Bank Promotions Bot"

Keep it concise, clear and easy to read on mobile.

Promotions data:
{all_promotions[:4000]}"""
                }
            ],
            max_tokens=2000,
            temperature=0.5
        )
        
        result = response.choices[0].message.content
        print("✅ Email digest created by AI")
        return result
        
    except Exception as e:
        error_msg = f"Email digest creation failed: {str(e)}"
        print(f"❌ {error_msg}")
        return error_msg


def test_ai_connection() -> bool:
    """
    Test if AI connection is working
    """
    try:
        response = client.chat.completions.create(
            model=FREE_MODEL,
            messages=[{"role": "user", "content": "Reply with just: OK"}],
            max_tokens=10
        )
        print("✅ OpenRouter AI connection successful!")
        return True
    except Exception as e:
        print(f"❌ OpenRouter AI connection failed: {str(e)}")
        return False