# scripts/emailer.py
# This file sends the promotion digest email via Gmail

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# Get email settings from .env file
GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL")


def create_html_email(text_content: str, promotions_data: list) -> str:
    """
    Convert plain text digest into beautiful HTML email
    """
    today = datetime.now().strftime("%A, %d %B %Y")
    
    # Create bank cards HTML
    bank_cards_html = ""
    for item in promotions_data:
        color = item.get("color", "#333333")
        bank_name = item.get("bank", "Unknown Bank")
        promotions = item.get("promotions", "No data")
        
        # Convert promotion text to HTML (replace newlines with <br>)
        promo_html = promotions.replace('\n', '<br>')
        
        bank_cards_html += f"""
        <div style="margin-bottom: 25px; border-radius: 10px; overflow: hidden; 
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <!-- Bank Header -->
            <div style="background-color: {color}; padding: 15px 20px;">
                <h2 style="color: white; margin: 0; font-size: 18px;">
                    🏦 {bank_name}
                </h2>
            </div>
            <!-- Bank Promotions -->
            <div style="background-color: #f9f9f9; padding: 20px; 
                        font-size: 14px; line-height: 1.8; color: #333;">
                {promo_html}
            </div>
        </div>
        """
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: Arial, sans-serif; background-color: #f0f2f5; 
                 margin: 0; padding: 20px;">
        
        <!-- Main Container -->
        <div style="max-width: 650px; margin: 0 auto; background-color: white; 
                    border-radius: 15px; overflow: hidden; 
                    box-shadow: 0 4px 20px rgba(0,0,0,0.15);">
            
            <!-- Header Banner -->
            <div style="background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); 
                        padding: 30px 25px; text-align: center;">
                <h1 style="color: white; margin: 0 0 8px 0; font-size: 24px;">
                    🏦 HK Bank Promotions
                </h1>
                <p style="color: #adb5bd; margin: 0; font-size: 14px;">
                    Weekly Digest — {today}
                </p>
                <div style="margin-top: 15px;">
                    <span style="background-color: #e74c3c; color: white; 
                                 padding: 5px 15px; border-radius: 20px; font-size: 12px;">
                        🔥 {len(promotions_data)} Banks Analyzed
                    </span>
                </div>
            </div>
            
            <!-- AI Summary Section -->
            <div style="padding: 25px; background-color: #fff3cd; 
                        border-left: 4px solid #ffc107;">
                <h3 style="margin: 0 0 10px 0; color: #856404; font-size: 16px;">
                    🤖 AI Weekly Summary
                </h3>
                <div style="font-size: 14px; color: #533f03; line-height: 1.8;">
                    {text_content.replace(chr(10), '<br>')}
                </div>
            </div>
            
            <!-- Bank by Bank Section -->
            <div style="padding: 25px;">
                <h2 style="color: #1a1a2e; font-size: 18px; margin: 0 0 20px 0; 
                           border-bottom: 2px solid #e9ecef; padding-bottom: 10px;">
                    📋 Promotions by Bank
                </h2>
                
                {bank_cards_html}
            </div>
            
            <!-- Footer -->
            <div style="background-color: #f8f9fa; padding: 20px 25px; 
                        text-align: center; border-top: 1px solid #e9ecef;">
                <p style="color: #6c757d; font-size: 12px; margin: 0;">
                    🤖 Auto-generated by HK Bank Promotions Bot<br>
                    Powered by OpenRouter AI • {today}
                </p>
                <p style="color: #adb5bd; font-size: 11px; margin: 10px 0 0 0;">
                    ⚠️ Always verify promotions directly with the bank before applying
                </p>
            </div>
        </div>
        
    </body>
    </html>
    """
    
    return html


def send_email(subject: str, text_content: str, promotions_data: list) -> bool:
    """
    Send the promotion digest email
    Returns True if successful, False if failed
    """
    print("\n" + "="*50)
    print("📧 SENDING EMAIL")
    print("="*50)
    
    # Check if email settings are configured
    if not GMAIL_ADDRESS or GMAIL_ADDRESS == "your.gmail@gmail.com":
        print("❌ Email not configured!")
        print("   Please update GMAIL_ADDRESS in your .env file")
        return False
    
    if not GMAIL_APP_PASSWORD or GMAIL_APP_PASSWORD == "xxxx-xxxx-xxxx-xxxx":
        print("❌ Gmail App Password not configured!")
        print("   Please update GMAIL_APP_PASSWORD in your .env file")
        return False
    
    if not RECIPIENT_EMAIL:
        print("❌ Recipient email not configured!")
        return False
    
    try:
        print(f"  📤 From: {GMAIL_ADDRESS}")
        print(f"  📥 To: {RECIPIENT_EMAIL}")
        print(f"  📌 Subject: {subject}")
        
        # Create email message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = f"HK Bank Bot <{GMAIL_ADDRESS}>"
        msg['To'] = RECIPIENT_EMAIL
        
        # Create plain text version (backup)
        plain_text = f"HK Bank Promotions Weekly Digest\n\n{text_content}"
        
        # Create HTML version (nice looking)
        html_content = create_html_email(text_content, promotions_data)
        
        # Attach both versions
        msg.attach(MIMEText(plain_text, 'plain', 'utf-8'))
        msg.attach(MIMEText(html_content, 'html', 'utf-8'))
        
        # Connect to Gmail and send
        print("  🔌 Connecting to Gmail...")
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.send_message(msg)
        
        print(f"  ✅ Email sent successfully to {RECIPIENT_EMAIL}!")
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail authentication failed!")
        print("   Make sure you're using Gmail App Password (not your regular password)")
        print("   Guide: https://support.google.com/accounts/answer/185833")
        return False
        
    except Exception as e:
        print(f"❌ Email failed: {str(e)}")
        return False


def send_test_email() -> bool:
    """
    Send a simple test email to verify settings work
    """
    print("\n🧪 Sending test email...")
    
    test_data = [
        {
            "bank": "Test Bank",
            "color": "#0080A1",
            "promotions": "✅ This is a test promotion\n💰 5% cashback on all purchases\n📅 Valid: Today"
        }
    ]
    
    today = datetime.now().strftime("%d %B %Y")
    
    return send_email(
        subject=f"✅ HK Bank Bot Test Email — {today}",
        text_content="This is a test email from your HK Bank Promotions Bot!\n\nIf you receive this, your email setup is working correctly. 🎉",
        promotions_data=test_data
    )


# Test - run this file directly to test email only
if __name__ == "__main__":
    result = send_test_email()
    if result:
        print("\n🎉 Test email sent! Check your inbox.")
    else:
        print("\n❌ Test email failed. Check your .env settings.")